// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Config
type SetConfigRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *SetConfigRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type SetConfigResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigResponse) Reset()         { *m = SetConfigResponse{} }
func (m *SetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetConfigResponse) ProtoMessage()    {}
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *SetConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigResponse.Unmarshal(m, b)
}
func (m *SetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigResponse.Merge(m, src)
}
func (m *SetConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetConfigResponse.Size(m)
}
func (m *SetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigResponse proto.InternalMessageInfo

func (m *SetConfigResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *SetConfigResponse) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *SetConfigResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *SetConfigResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type AlterConfigRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlterConfigRequest) Reset()         { *m = AlterConfigRequest{} }
func (m *AlterConfigRequest) String() string { return proto.CompactTextString(m) }
func (*AlterConfigRequest) ProtoMessage()    {}
func (*AlterConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *AlterConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlterConfigRequest.Unmarshal(m, b)
}
func (m *AlterConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlterConfigRequest.Marshal(b, m, deterministic)
}
func (m *AlterConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlterConfigRequest.Merge(m, src)
}
func (m *AlterConfigRequest) XXX_Size() int {
	return xxx_messageInfo_AlterConfigRequest.Size(m)
}
func (m *AlterConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AlterConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AlterConfigRequest proto.InternalMessageInfo

func (m *AlterConfigRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *AlterConfigRequest) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

type AlterConfigResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AlterConfigResponse) Reset()         { *m = AlterConfigResponse{} }
func (m *AlterConfigResponse) String() string { return proto.CompactTextString(m) }
func (*AlterConfigResponse) ProtoMessage()    {}
func (*AlterConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *AlterConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AlterConfigResponse.Unmarshal(m, b)
}
func (m *AlterConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AlterConfigResponse.Marshal(b, m, deterministic)
}
func (m *AlterConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AlterConfigResponse.Merge(m, src)
}
func (m *AlterConfigResponse) XXX_Size() int {
	return xxx_messageInfo_AlterConfigResponse.Size(m)
}
func (m *AlterConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AlterConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AlterConfigResponse proto.InternalMessageInfo

func (m *AlterConfigResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *AlterConfigResponse) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *AlterConfigResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *AlterConfigResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type ShowConfigRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowConfigRequest) Reset()         { *m = ShowConfigRequest{} }
func (m *ShowConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ShowConfigRequest) ProtoMessage()    {}
func (*ShowConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *ShowConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowConfigRequest.Unmarshal(m, b)
}
func (m *ShowConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowConfigRequest.Marshal(b, m, deterministic)
}
func (m *ShowConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowConfigRequest.Merge(m, src)
}
func (m *ShowConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ShowConfigRequest.Size(m)
}
func (m *ShowConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShowConfigRequest proto.InternalMessageInfo

func (m *ShowConfigRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

type ShowConfigResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Config               []byte   `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowConfigResponse) Reset()         { *m = ShowConfigResponse{} }
func (m *ShowConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ShowConfigResponse) ProtoMessage()    {}
func (*ShowConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *ShowConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowConfigResponse.Unmarshal(m, b)
}
func (m *ShowConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowConfigResponse.Marshal(b, m, deterministic)
}
func (m *ShowConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowConfigResponse.Merge(m, src)
}
func (m *ShowConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ShowConfigResponse.Size(m)
}
func (m *ShowConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShowConfigResponse proto.InternalMessageInfo

func (m *ShowConfigResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *ShowConfigResponse) GetConfig() []byte {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ShowConfigResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *ShowConfigResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type ListTopicRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTopicRequest) Reset()         { *m = ListTopicRequest{} }
func (m *ListTopicRequest) String() string { return proto.CompactTextString(m) }
func (*ListTopicRequest) ProtoMessage()    {}
func (*ListTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *ListTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTopicRequest.Unmarshal(m, b)
}
func (m *ListTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTopicRequest.Marshal(b, m, deterministic)
}
func (m *ListTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTopicRequest.Merge(m, src)
}
func (m *ListTopicRequest) XXX_Size() int {
	return xxx_messageInfo_ListTopicRequest.Size(m)
}
func (m *ListTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTopicRequest proto.InternalMessageInfo

func (m *ListTopicRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

type ListTopicResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Topics               []string `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTopicResponse) Reset()         { *m = ListTopicResponse{} }
func (m *ListTopicResponse) String() string { return proto.CompactTextString(m) }
func (*ListTopicResponse) ProtoMessage()    {}
func (*ListTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *ListTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTopicResponse.Unmarshal(m, b)
}
func (m *ListTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTopicResponse.Marshal(b, m, deterministic)
}
func (m *ListTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTopicResponse.Merge(m, src)
}
func (m *ListTopicResponse) XXX_Size() int {
	return xxx_messageInfo_ListTopicResponse.Size(m)
}
func (m *ListTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListTopicResponse proto.InternalMessageInfo

func (m *ListTopicResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *ListTopicResponse) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *ListTopicResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *ListTopicResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type DescribeTopicRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeTopicRequest) Reset()         { *m = DescribeTopicRequest{} }
func (m *DescribeTopicRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeTopicRequest) ProtoMessage()    {}
func (*DescribeTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *DescribeTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeTopicRequest.Unmarshal(m, b)
}
func (m *DescribeTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeTopicRequest.Marshal(b, m, deterministic)
}
func (m *DescribeTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeTopicRequest.Merge(m, src)
}
func (m *DescribeTopicRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeTopicRequest.Size(m)
}
func (m *DescribeTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeTopicRequest proto.InternalMessageInfo

func (m *DescribeTopicRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *DescribeTopicRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type DescribeTopicResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Topic                *Topic   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeTopicResponse) Reset()         { *m = DescribeTopicResponse{} }
func (m *DescribeTopicResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeTopicResponse) ProtoMessage()    {}
func (*DescribeTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *DescribeTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeTopicResponse.Unmarshal(m, b)
}
func (m *DescribeTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeTopicResponse.Marshal(b, m, deterministic)
}
func (m *DescribeTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeTopicResponse.Merge(m, src)
}
func (m *DescribeTopicResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeTopicResponse.Size(m)
}
func (m *DescribeTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeTopicResponse proto.InternalMessageInfo

func (m *DescribeTopicResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *DescribeTopicResponse) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

func (m *DescribeTopicResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *DescribeTopicResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type CreateTopicRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	TopicDescription     string   `protobuf:"bytes,3,opt,name=topic_description,json=topicDescription,proto3" json:"topic_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicRequest) Reset()         { *m = CreateTopicRequest{} }
func (m *CreateTopicRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTopicRequest) ProtoMessage()    {}
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *CreateTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicRequest.Unmarshal(m, b)
}
func (m *CreateTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicRequest.Marshal(b, m, deterministic)
}
func (m *CreateTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicRequest.Merge(m, src)
}
func (m *CreateTopicRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTopicRequest.Size(m)
}
func (m *CreateTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicRequest proto.InternalMessageInfo

func (m *CreateTopicRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *CreateTopicRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *CreateTopicRequest) GetTopicDescription() string {
	if m != nil {
		return m.TopicDescription
	}
	return ""
}

type CreateTopicResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTopicResponse) Reset()         { *m = CreateTopicResponse{} }
func (m *CreateTopicResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTopicResponse) ProtoMessage()    {}
func (*CreateTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *CreateTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTopicResponse.Unmarshal(m, b)
}
func (m *CreateTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTopicResponse.Marshal(b, m, deterministic)
}
func (m *CreateTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTopicResponse.Merge(m, src)
}
func (m *CreateTopicResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTopicResponse.Size(m)
}
func (m *CreateTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTopicResponse proto.InternalMessageInfo

func (m *CreateTopicResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *CreateTopicResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreateTopicResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type DeleteTopicRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTopicRequest) Reset()         { *m = DeleteTopicRequest{} }
func (m *DeleteTopicRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTopicRequest) ProtoMessage()    {}
func (*DeleteTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *DeleteTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTopicRequest.Unmarshal(m, b)
}
func (m *DeleteTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTopicRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTopicRequest.Merge(m, src)
}
func (m *DeleteTopicRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTopicRequest.Size(m)
}
func (m *DeleteTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTopicRequest proto.InternalMessageInfo

func (m *DeleteTopicRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *DeleteTopicRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type DeleteTopicResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTopicResponse) Reset()         { *m = DeleteTopicResponse{} }
func (m *DeleteTopicResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTopicResponse) ProtoMessage()    {}
func (*DeleteTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *DeleteTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTopicResponse.Unmarshal(m, b)
}
func (m *DeleteTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTopicResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTopicResponse.Merge(m, src)
}
func (m *DeleteTopicResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTopicResponse.Size(m)
}
func (m *DeleteTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTopicResponse proto.InternalMessageInfo

func (m *DeleteTopicResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *DeleteTopicResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *DeleteTopicResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// fragment
type CreateFragmentRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFragmentRequest) Reset()         { *m = CreateFragmentRequest{} }
func (m *CreateFragmentRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFragmentRequest) ProtoMessage()    {}
func (*CreateFragmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *CreateFragmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFragmentRequest.Unmarshal(m, b)
}
func (m *CreateFragmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFragmentRequest.Marshal(b, m, deterministic)
}
func (m *CreateFragmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFragmentRequest.Merge(m, src)
}
func (m *CreateFragmentRequest) XXX_Size() int {
	return xxx_messageInfo_CreateFragmentRequest.Size(m)
}
func (m *CreateFragmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFragmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFragmentRequest proto.InternalMessageInfo

func (m *CreateFragmentRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *CreateFragmentRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type CreateFragmentResponse struct {
	Magic                int32     `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Fragment             *Fragment `protobuf:"bytes,2,opt,name=fragment,proto3" json:"fragment,omitempty"`
	ErrorCode            int32     `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string    `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateFragmentResponse) Reset()         { *m = CreateFragmentResponse{} }
func (m *CreateFragmentResponse) String() string { return proto.CompactTextString(m) }
func (*CreateFragmentResponse) ProtoMessage()    {}
func (*CreateFragmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *CreateFragmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateFragmentResponse.Unmarshal(m, b)
}
func (m *CreateFragmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateFragmentResponse.Marshal(b, m, deterministic)
}
func (m *CreateFragmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFragmentResponse.Merge(m, src)
}
func (m *CreateFragmentResponse) XXX_Size() int {
	return xxx_messageInfo_CreateFragmentResponse.Size(m)
}
func (m *CreateFragmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFragmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFragmentResponse proto.InternalMessageInfo

func (m *CreateFragmentResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *CreateFragmentResponse) GetFragment() *Fragment {
	if m != nil {
		return m.Fragment
	}
	return nil
}

func (m *CreateFragmentResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreateFragmentResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type DeleteFragmentRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	FragmentId           uint32   `protobuf:"varint,3,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFragmentRequest) Reset()         { *m = DeleteFragmentRequest{} }
func (m *DeleteFragmentRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteFragmentRequest) ProtoMessage()    {}
func (*DeleteFragmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *DeleteFragmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFragmentRequest.Unmarshal(m, b)
}
func (m *DeleteFragmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFragmentRequest.Marshal(b, m, deterministic)
}
func (m *DeleteFragmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFragmentRequest.Merge(m, src)
}
func (m *DeleteFragmentRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteFragmentRequest.Size(m)
}
func (m *DeleteFragmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFragmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFragmentRequest proto.InternalMessageInfo

func (m *DeleteFragmentRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *DeleteFragmentRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *DeleteFragmentRequest) GetFragmentId() uint32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

type DeleteFragmentResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteFragmentResponse) Reset()         { *m = DeleteFragmentResponse{} }
func (m *DeleteFragmentResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteFragmentResponse) ProtoMessage()    {}
func (*DeleteFragmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *DeleteFragmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteFragmentResponse.Unmarshal(m, b)
}
func (m *DeleteFragmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteFragmentResponse.Marshal(b, m, deterministic)
}
func (m *DeleteFragmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteFragmentResponse.Merge(m, src)
}
func (m *DeleteFragmentResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteFragmentResponse.Size(m)
}
func (m *DeleteFragmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteFragmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteFragmentResponse proto.InternalMessageInfo

func (m *DeleteFragmentResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *DeleteFragmentResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *DeleteFragmentResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type DescribeFragmentRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	FragmentId           uint32   `protobuf:"varint,3,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeFragmentRequest) Reset()         { *m = DescribeFragmentRequest{} }
func (m *DescribeFragmentRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeFragmentRequest) ProtoMessage()    {}
func (*DescribeFragmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *DescribeFragmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeFragmentRequest.Unmarshal(m, b)
}
func (m *DescribeFragmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeFragmentRequest.Marshal(b, m, deterministic)
}
func (m *DescribeFragmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeFragmentRequest.Merge(m, src)
}
func (m *DescribeFragmentRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeFragmentRequest.Size(m)
}
func (m *DescribeFragmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeFragmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeFragmentRequest proto.InternalMessageInfo

func (m *DescribeFragmentRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *DescribeFragmentRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *DescribeFragmentRequest) GetFragmentId() uint32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

type DescribeFragmentResponse struct {
	Magic                int32     `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Fragment             *Fragment `protobuf:"bytes,2,opt,name=fragment,proto3" json:"fragment,omitempty"`
	ErrorCode            int32     `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string    `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DescribeFragmentResponse) Reset()         { *m = DescribeFragmentResponse{} }
func (m *DescribeFragmentResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeFragmentResponse) ProtoMessage()    {}
func (*DescribeFragmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *DescribeFragmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeFragmentResponse.Unmarshal(m, b)
}
func (m *DescribeFragmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeFragmentResponse.Marshal(b, m, deterministic)
}
func (m *DescribeFragmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeFragmentResponse.Merge(m, src)
}
func (m *DescribeFragmentResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeFragmentResponse.Size(m)
}
func (m *DescribeFragmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeFragmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeFragmentResponse proto.InternalMessageInfo

func (m *DescribeFragmentResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *DescribeFragmentResponse) GetFragment() *Fragment {
	if m != nil {
		return m.Fragment
	}
	return nil
}

func (m *DescribeFragmentResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *DescribeFragmentResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// group
type CreateGroupRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	GroupName            string   `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupRequest) Reset()         { *m = CreateGroupRequest{} }
func (m *CreateGroupRequest) String() string { return proto.CompactTextString(m) }
func (*CreateGroupRequest) ProtoMessage()    {}
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *CreateGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupRequest.Unmarshal(m, b)
}
func (m *CreateGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupRequest.Marshal(b, m, deterministic)
}
func (m *CreateGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupRequest.Merge(m, src)
}
func (m *CreateGroupRequest) XXX_Size() int {
	return xxx_messageInfo_CreateGroupRequest.Size(m)
}
func (m *CreateGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupRequest proto.InternalMessageInfo

func (m *CreateGroupRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *CreateGroupRequest) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *CreateGroupRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateGroupResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Group                *Group   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGroupResponse) Reset()         { *m = CreateGroupResponse{} }
func (m *CreateGroupResponse) String() string { return proto.CompactTextString(m) }
func (*CreateGroupResponse) ProtoMessage()    {}
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *CreateGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGroupResponse.Unmarshal(m, b)
}
func (m *CreateGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGroupResponse.Marshal(b, m, deterministic)
}
func (m *CreateGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGroupResponse.Merge(m, src)
}
func (m *CreateGroupResponse) XXX_Size() int {
	return xxx_messageInfo_CreateGroupResponse.Size(m)
}
func (m *CreateGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGroupResponse proto.InternalMessageInfo

func (m *CreateGroupResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *CreateGroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *CreateGroupResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CreateGroupResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type ListGroupsRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsRequest) Reset()         { *m = ListGroupsRequest{} }
func (m *ListGroupsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGroupsRequest) ProtoMessage()    {}
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *ListGroupsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsRequest.Unmarshal(m, b)
}
func (m *ListGroupsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsRequest.Marshal(b, m, deterministic)
}
func (m *ListGroupsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsRequest.Merge(m, src)
}
func (m *ListGroupsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGroupsRequest.Size(m)
}
func (m *ListGroupsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsRequest proto.InternalMessageInfo

func (m *ListGroupsRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

type ListGroupsResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Group                []*Group `protobuf:"bytes,2,rep,name=group,proto3" json:"group,omitempty"`
	ErrorCode            int32    `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGroupsResponse) Reset()         { *m = ListGroupsResponse{} }
func (m *ListGroupsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGroupsResponse) ProtoMessage()    {}
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *ListGroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGroupsResponse.Unmarshal(m, b)
}
func (m *ListGroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGroupsResponse.Marshal(b, m, deterministic)
}
func (m *ListGroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGroupsResponse.Merge(m, src)
}
func (m *ListGroupsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGroupsResponse.Size(m)
}
func (m *ListGroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGroupsResponse proto.InternalMessageInfo

func (m *ListGroupsResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *ListGroupsResponse) GetGroup() []*Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *ListGroupsResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *ListGroupsResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// Consumer can join only one group
type JoinGroupRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	GroupId              uint64   `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGroupRequest) Reset()         { *m = JoinGroupRequest{} }
func (m *JoinGroupRequest) String() string { return proto.CompactTextString(m) }
func (*JoinGroupRequest) ProtoMessage()    {}
func (*JoinGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{24}
}

func (m *JoinGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGroupRequest.Unmarshal(m, b)
}
func (m *JoinGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGroupRequest.Marshal(b, m, deterministic)
}
func (m *JoinGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGroupRequest.Merge(m, src)
}
func (m *JoinGroupRequest) XXX_Size() int {
	return xxx_messageInfo_JoinGroupRequest.Size(m)
}
func (m *JoinGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGroupRequest proto.InternalMessageInfo

func (m *JoinGroupRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *JoinGroupRequest) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type JoinGroupResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinGroupResponse) Reset()         { *m = JoinGroupResponse{} }
func (m *JoinGroupResponse) String() string { return proto.CompactTextString(m) }
func (*JoinGroupResponse) ProtoMessage()    {}
func (*JoinGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{25}
}

func (m *JoinGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinGroupResponse.Unmarshal(m, b)
}
func (m *JoinGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinGroupResponse.Marshal(b, m, deterministic)
}
func (m *JoinGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinGroupResponse.Merge(m, src)
}
func (m *JoinGroupResponse) XXX_Size() int {
	return xxx_messageInfo_JoinGroupResponse.Size(m)
}
func (m *JoinGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinGroupResponse proto.InternalMessageInfo

func (m *JoinGroupResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *JoinGroupResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *JoinGroupResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type LeaveGroupRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	GroupId              uint64   `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveGroupRequest) Reset()         { *m = LeaveGroupRequest{} }
func (m *LeaveGroupRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveGroupRequest) ProtoMessage()    {}
func (*LeaveGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{26}
}

func (m *LeaveGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveGroupRequest.Unmarshal(m, b)
}
func (m *LeaveGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveGroupRequest.Marshal(b, m, deterministic)
}
func (m *LeaveGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveGroupRequest.Merge(m, src)
}
func (m *LeaveGroupRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveGroupRequest.Size(m)
}
func (m *LeaveGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveGroupRequest proto.InternalMessageInfo

func (m *LeaveGroupRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *LeaveGroupRequest) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type LeaveGroupResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveGroupResponse) Reset()         { *m = LeaveGroupResponse{} }
func (m *LeaveGroupResponse) String() string { return proto.CompactTextString(m) }
func (*LeaveGroupResponse) ProtoMessage()    {}
func (*LeaveGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{27}
}

func (m *LeaveGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveGroupResponse.Unmarshal(m, b)
}
func (m *LeaveGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveGroupResponse.Marshal(b, m, deterministic)
}
func (m *LeaveGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveGroupResponse.Merge(m, src)
}
func (m *LeaveGroupResponse) XXX_Size() int {
	return xxx_messageInfo_LeaveGroupResponse.Size(m)
}
func (m *LeaveGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveGroupResponse proto.InternalMessageInfo

func (m *LeaveGroupResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *LeaveGroupResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *LeaveGroupResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

// Note:: Only group owner can delete group
type DeleteGroupRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	GroupId              uint64   `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupRequest) Reset()         { *m = DeleteGroupRequest{} }
func (m *DeleteGroupRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupRequest) ProtoMessage()    {}
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{28}
}

func (m *DeleteGroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupRequest.Unmarshal(m, b)
}
func (m *DeleteGroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupRequest.Marshal(b, m, deterministic)
}
func (m *DeleteGroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupRequest.Merge(m, src)
}
func (m *DeleteGroupRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupRequest.Size(m)
}
func (m *DeleteGroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupRequest proto.InternalMessageInfo

func (m *DeleteGroupRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *DeleteGroupRequest) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

type DeleteGroupResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteGroupResponse) Reset()         { *m = DeleteGroupResponse{} }
func (m *DeleteGroupResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteGroupResponse) ProtoMessage()    {}
func (*DeleteGroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{29}
}

func (m *DeleteGroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteGroupResponse.Unmarshal(m, b)
}
func (m *DeleteGroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteGroupResponse.Marshal(b, m, deterministic)
}
func (m *DeleteGroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteGroupResponse.Merge(m, src)
}
func (m *DeleteGroupResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteGroupResponse.Size(m)
}
func (m *DeleteGroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteGroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteGroupResponse proto.InternalMessageInfo

func (m *DeleteGroupResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *DeleteGroupResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *DeleteGroupResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type ConnectRequest struct {
	Magic                int32       `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	SessionType          SessionType `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=shapleq.proto.SessionType" json:"session_type,omitempty"`
	TopicName            string      `protobuf:"bytes,3,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	FragmentIds          []uint32    `protobuf:"varint,4,rep,packed,name=fragment_ids,json=fragmentIds,proto3" json:"fragment_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConnectRequest) Reset()         { *m = ConnectRequest{} }
func (m *ConnectRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectRequest) ProtoMessage()    {}
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{30}
}

func (m *ConnectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectRequest.Unmarshal(m, b)
}
func (m *ConnectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectRequest.Marshal(b, m, deterministic)
}
func (m *ConnectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectRequest.Merge(m, src)
}
func (m *ConnectRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectRequest.Size(m)
}
func (m *ConnectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectRequest proto.InternalMessageInfo

func (m *ConnectRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *ConnectRequest) GetSessionType() SessionType {
	if m != nil {
		return m.SessionType
	}
	return SessionType_ADMIN
}

func (m *ConnectRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ConnectRequest) GetFragmentIds() []uint32 {
	if m != nil {
		return m.FragmentIds
	}
	return nil
}

type ConnectResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{31}
}

func (m *ConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectResponse.Unmarshal(m, b)
}
func (m *ConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectResponse.Marshal(b, m, deterministic)
}
func (m *ConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectResponse.Merge(m, src)
}
func (m *ConnectResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectResponse.Size(m)
}
func (m *ConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectResponse proto.InternalMessageInfo

func (m *ConnectResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

type Ping struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Echo                 string   `protobuf:"bytes,2,opt,name=echo,proto3" json:"echo,omitempty"`
	BrokerId             uint64   `protobuf:"varint,3,opt,name=broker_id,json=brokerId,proto3" json:"broker_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{32}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Ping) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func (m *Ping) GetBrokerId() uint64 {
	if m != nil {
		return m.BrokerId
	}
	return 0
}

type Pong struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Echo                 string   `protobuf:"bytes,2,opt,name=echo,proto3" json:"echo,omitempty"`
	ServerVersion        uint32   `protobuf:"varint,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ServerTime           uint64   `protobuf:"varint,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{33}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Pong) GetEcho() string {
	if m != nil {
		return m.Echo
	}
	return ""
}

func (m *Pong) GetServerVersion() uint32 {
	if m != nil {
		return m.ServerVersion
	}
	return 0
}

func (m *Pong) GetServerTime() uint64 {
	if m != nil {
		return m.ServerTime
	}
	return 0
}

type PutRequest struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	SeqNum               uint64   `protobuf:"varint,3,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	NodeId               string   `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FragmentId           uint32   `protobuf:"varint,5,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutRequest) Reset()         { *m = PutRequest{} }
func (m *PutRequest) String() string { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()    {}
func (*PutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{34}
}

func (m *PutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutRequest.Unmarshal(m, b)
}
func (m *PutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutRequest.Marshal(b, m, deterministic)
}
func (m *PutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutRequest.Merge(m, src)
}
func (m *PutRequest) XXX_Size() int {
	return xxx_messageInfo_PutRequest.Size(m)
}
func (m *PutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutRequest proto.InternalMessageInfo

func (m *PutRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *PutRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PutRequest) GetSeqNum() uint64 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *PutRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *PutRequest) GetFragmentId() uint32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

type PutResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	FragmentId           uint32   `protobuf:"varint,3,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	LastOffset           uint64   `protobuf:"varint,4,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutResponse) Reset()         { *m = PutResponse{} }
func (m *PutResponse) String() string { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()    {}
func (*PutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{35}
}

func (m *PutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutResponse.Unmarshal(m, b)
}
func (m *PutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutResponse.Marshal(b, m, deterministic)
}
func (m *PutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutResponse.Merge(m, src)
}
func (m *PutResponse) XXX_Size() int {
	return xxx_messageInfo_PutResponse.Size(m)
}
func (m *PutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutResponse proto.InternalMessageInfo

func (m *PutResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *PutResponse) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *PutResponse) GetFragmentId() uint32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *PutResponse) GetLastOffset() uint64 {
	if m != nil {
		return m.LastOffset
	}
	return 0
}

type FetchRequest struct {
	Magic                int32                      `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	MaxBatchSize         uint32                     `protobuf:"varint,2,opt,name=max_batch_size,json=maxBatchSize,proto3" json:"max_batch_size,omitempty"`
	FlushInterval        uint32                     `protobuf:"varint,3,opt,name=flush_interval,json=flushInterval,proto3" json:"flush_interval,omitempty"`
	FragmentOffsets      []*FetchRequest_OffsetInfo `protobuf:"bytes,4,rep,name=fragmentOffsets,proto3" json:"fragmentOffsets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{36}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func (m *FetchRequest) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *FetchRequest) GetMaxBatchSize() uint32 {
	if m != nil {
		return m.MaxBatchSize
	}
	return 0
}

func (m *FetchRequest) GetFlushInterval() uint32 {
	if m != nil {
		return m.FlushInterval
	}
	return 0
}

func (m *FetchRequest) GetFragmentOffsets() []*FetchRequest_OffsetInfo {
	if m != nil {
		return m.FragmentOffsets
	}
	return nil
}

type FetchRequest_OffsetInfo struct {
	FragmentId           uint32   `protobuf:"varint,1,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	StartOffset          uint64   `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest_OffsetInfo) Reset()         { *m = FetchRequest_OffsetInfo{} }
func (m *FetchRequest_OffsetInfo) String() string { return proto.CompactTextString(m) }
func (*FetchRequest_OffsetInfo) ProtoMessage()    {}
func (*FetchRequest_OffsetInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{36, 0}
}

func (m *FetchRequest_OffsetInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest_OffsetInfo.Unmarshal(m, b)
}
func (m *FetchRequest_OffsetInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest_OffsetInfo.Marshal(b, m, deterministic)
}
func (m *FetchRequest_OffsetInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest_OffsetInfo.Merge(m, src)
}
func (m *FetchRequest_OffsetInfo) XXX_Size() int {
	return xxx_messageInfo_FetchRequest_OffsetInfo.Size(m)
}
func (m *FetchRequest_OffsetInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest_OffsetInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest_OffsetInfo proto.InternalMessageInfo

func (m *FetchRequest_OffsetInfo) GetFragmentId() uint32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *FetchRequest_OffsetInfo) GetStartOffset() uint64 {
	if m != nil {
		return m.StartOffset
	}
	return 0
}

type FetchResponse struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	SeqNum               uint64   `protobuf:"varint,4,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	NodeId               string   `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TopicName            string   `protobuf:"bytes,6,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	FragmentId           uint32   `protobuf:"varint,7,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	LastOffset           uint64   `protobuf:"varint,8,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchResponse) Reset()         { *m = FetchResponse{} }
func (m *FetchResponse) String() string { return proto.CompactTextString(m) }
func (*FetchResponse) ProtoMessage()    {}
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{37}
}

func (m *FetchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchResponse.Unmarshal(m, b)
}
func (m *FetchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchResponse.Marshal(b, m, deterministic)
}
func (m *FetchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchResponse.Merge(m, src)
}
func (m *FetchResponse) XXX_Size() int {
	return xxx_messageInfo_FetchResponse.Size(m)
}
func (m *FetchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchResponse proto.InternalMessageInfo

func (m *FetchResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *FetchResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *FetchResponse) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FetchResponse) GetSeqNum() uint64 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *FetchResponse) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *FetchResponse) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *FetchResponse) GetFragmentId() uint32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *FetchResponse) GetLastOffset() uint64 {
	if m != nil {
		return m.LastOffset
	}
	return 0
}

type BatchedFetchResponse struct {
	Magic                int32                           `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Items                []*BatchedFetchResponse_Fetched `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	LastOffset           uint64                          `protobuf:"varint,3,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *BatchedFetchResponse) Reset()         { *m = BatchedFetchResponse{} }
func (m *BatchedFetchResponse) String() string { return proto.CompactTextString(m) }
func (*BatchedFetchResponse) ProtoMessage()    {}
func (*BatchedFetchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{38}
}

func (m *BatchedFetchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchedFetchResponse.Unmarshal(m, b)
}
func (m *BatchedFetchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchedFetchResponse.Marshal(b, m, deterministic)
}
func (m *BatchedFetchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchedFetchResponse.Merge(m, src)
}
func (m *BatchedFetchResponse) XXX_Size() int {
	return xxx_messageInfo_BatchedFetchResponse.Size(m)
}
func (m *BatchedFetchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchedFetchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BatchedFetchResponse proto.InternalMessageInfo

func (m *BatchedFetchResponse) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *BatchedFetchResponse) GetItems() []*BatchedFetchResponse_Fetched {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *BatchedFetchResponse) GetLastOffset() uint64 {
	if m != nil {
		return m.LastOffset
	}
	return 0
}

type BatchedFetchResponse_Fetched struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Offset               uint64   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	SeqNum               uint64   `protobuf:"varint,3,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	NodeId               string   `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TopicName            string   `protobuf:"bytes,5,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	FragmentId           uint32   `protobuf:"varint,6,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchedFetchResponse_Fetched) Reset()         { *m = BatchedFetchResponse_Fetched{} }
func (m *BatchedFetchResponse_Fetched) String() string { return proto.CompactTextString(m) }
func (*BatchedFetchResponse_Fetched) ProtoMessage()    {}
func (*BatchedFetchResponse_Fetched) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{38, 0}
}

func (m *BatchedFetchResponse_Fetched) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchedFetchResponse_Fetched.Unmarshal(m, b)
}
func (m *BatchedFetchResponse_Fetched) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchedFetchResponse_Fetched.Marshal(b, m, deterministic)
}
func (m *BatchedFetchResponse_Fetched) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchedFetchResponse_Fetched.Merge(m, src)
}
func (m *BatchedFetchResponse_Fetched) XXX_Size() int {
	return xxx_messageInfo_BatchedFetchResponse_Fetched.Size(m)
}
func (m *BatchedFetchResponse_Fetched) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchedFetchResponse_Fetched.DiscardUnknown(m)
}

var xxx_messageInfo_BatchedFetchResponse_Fetched proto.InternalMessageInfo

func (m *BatchedFetchResponse_Fetched) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BatchedFetchResponse_Fetched) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *BatchedFetchResponse_Fetched) GetSeqNum() uint64 {
	if m != nil {
		return m.SeqNum
	}
	return 0
}

func (m *BatchedFetchResponse_Fetched) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *BatchedFetchResponse_Fetched) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *BatchedFetchResponse_Fetched) GetFragmentId() uint32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

type Ack struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{39}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *Ack) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Ack) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type Close struct {
	Magic                int32    `protobuf:"varint,1,opt,name=magic,proto3" json:"magic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Close) Reset()         { *m = Close{} }
func (m *Close) String() string { return proto.CompactTextString(m) }
func (*Close) ProtoMessage()    {}
func (*Close) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{40}
}

func (m *Close) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Close.Unmarshal(m, b)
}
func (m *Close) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Close.Marshal(b, m, deterministic)
}
func (m *Close) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Close.Merge(m, src)
}
func (m *Close) XXX_Size() int {
	return xxx_messageInfo_Close.Size(m)
}
func (m *Close) XXX_DiscardUnknown() {
	xxx_messageInfo_Close.DiscardUnknown(m)
}

var xxx_messageInfo_Close proto.InternalMessageInfo

func (m *Close) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func init() {
	proto.RegisterType((*SetConfigRequest)(nil), "shapleq.proto.SetConfigRequest")
	proto.RegisterType((*SetConfigResponse)(nil), "shapleq.proto.SetConfigResponse")
	proto.RegisterType((*AlterConfigRequest)(nil), "shapleq.proto.AlterConfigRequest")
	proto.RegisterType((*AlterConfigResponse)(nil), "shapleq.proto.AlterConfigResponse")
	proto.RegisterType((*ShowConfigRequest)(nil), "shapleq.proto.ShowConfigRequest")
	proto.RegisterType((*ShowConfigResponse)(nil), "shapleq.proto.ShowConfigResponse")
	proto.RegisterType((*ListTopicRequest)(nil), "shapleq.proto.ListTopicRequest")
	proto.RegisterType((*ListTopicResponse)(nil), "shapleq.proto.ListTopicResponse")
	proto.RegisterType((*DescribeTopicRequest)(nil), "shapleq.proto.DescribeTopicRequest")
	proto.RegisterType((*DescribeTopicResponse)(nil), "shapleq.proto.DescribeTopicResponse")
	proto.RegisterType((*CreateTopicRequest)(nil), "shapleq.proto.CreateTopicRequest")
	proto.RegisterType((*CreateTopicResponse)(nil), "shapleq.proto.CreateTopicResponse")
	proto.RegisterType((*DeleteTopicRequest)(nil), "shapleq.proto.DeleteTopicRequest")
	proto.RegisterType((*DeleteTopicResponse)(nil), "shapleq.proto.DeleteTopicResponse")
	proto.RegisterType((*CreateFragmentRequest)(nil), "shapleq.proto.CreateFragmentRequest")
	proto.RegisterType((*CreateFragmentResponse)(nil), "shapleq.proto.CreateFragmentResponse")
	proto.RegisterType((*DeleteFragmentRequest)(nil), "shapleq.proto.DeleteFragmentRequest")
	proto.RegisterType((*DeleteFragmentResponse)(nil), "shapleq.proto.DeleteFragmentResponse")
	proto.RegisterType((*DescribeFragmentRequest)(nil), "shapleq.proto.DescribeFragmentRequest")
	proto.RegisterType((*DescribeFragmentResponse)(nil), "shapleq.proto.DescribeFragmentResponse")
	proto.RegisterType((*CreateGroupRequest)(nil), "shapleq.proto.CreateGroupRequest")
	proto.RegisterType((*CreateGroupResponse)(nil), "shapleq.proto.CreateGroupResponse")
	proto.RegisterType((*ListGroupsRequest)(nil), "shapleq.proto.ListGroupsRequest")
	proto.RegisterType((*ListGroupsResponse)(nil), "shapleq.proto.ListGroupsResponse")
	proto.RegisterType((*JoinGroupRequest)(nil), "shapleq.proto.JoinGroupRequest")
	proto.RegisterType((*JoinGroupResponse)(nil), "shapleq.proto.JoinGroupResponse")
	proto.RegisterType((*LeaveGroupRequest)(nil), "shapleq.proto.LeaveGroupRequest")
	proto.RegisterType((*LeaveGroupResponse)(nil), "shapleq.proto.LeaveGroupResponse")
	proto.RegisterType((*DeleteGroupRequest)(nil), "shapleq.proto.DeleteGroupRequest")
	proto.RegisterType((*DeleteGroupResponse)(nil), "shapleq.proto.DeleteGroupResponse")
	proto.RegisterType((*ConnectRequest)(nil), "shapleq.proto.ConnectRequest")
	proto.RegisterType((*ConnectResponse)(nil), "shapleq.proto.ConnectResponse")
	proto.RegisterType((*Ping)(nil), "shapleq.proto.Ping")
	proto.RegisterType((*Pong)(nil), "shapleq.proto.Pong")
	proto.RegisterType((*PutRequest)(nil), "shapleq.proto.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "shapleq.proto.PutResponse")
	proto.RegisterType((*FetchRequest)(nil), "shapleq.proto.FetchRequest")
	proto.RegisterType((*FetchRequest_OffsetInfo)(nil), "shapleq.proto.FetchRequest.OffsetInfo")
	proto.RegisterType((*FetchResponse)(nil), "shapleq.proto.FetchResponse")
	proto.RegisterType((*BatchedFetchResponse)(nil), "shapleq.proto.BatchedFetchResponse")
	proto.RegisterType((*BatchedFetchResponse_Fetched)(nil), "shapleq.proto.BatchedFetchResponse.Fetched")
	proto.RegisterType((*Ack)(nil), "shapleq.proto.Ack")
	proto.RegisterType((*Close)(nil), "shapleq.proto.Close")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1075 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x06, 0x25, 0x4a, 0xb6, 0x46, 0x92, 0x63, 0x6f, 0x1c, 0x5b, 0x75, 0x11, 0x54, 0x61, 0xff,
	0xd4, 0x06, 0x50, 0x01, 0xe7, 0x5c, 0xa0, 0xb6, 0xdc, 0x14, 0x6a, 0x9d, 0x54, 0xa0, 0x8d, 0x1e,
	0x7a, 0x21, 0x28, 0x72, 0x24, 0x11, 0x16, 0xb9, 0x34, 0x77, 0xa5, 0x3a, 0x39, 0xf7, 0x07, 0x7d,
	0x80, 0x5e, 0x5a, 0xf4, 0x6c, 0xf4, 0x15, 0xfa, 0x3c, 0x7d, 0x90, 0x82, 0xbb, 0xa4, 0x4c, 0x51,
	0x96, 0xa8, 0x40, 0xb2, 0x93, 0x1b, 0x77, 0x76, 0x76, 0xf6, 0xfb, 0xbe, 0x99, 0x9d, 0x01, 0xa1,
	0x64, 0xfa, 0x4e, 0xd3, 0x0f, 0x28, 0xa7, 0xa4, 0xca, 0x06, 0xa6, 0x3f, 0xc4, 0x4b, 0xb9, 0x3c,
	0x00, 0xdb, 0xe4, 0xa6, 0xfc, 0xd6, 0xbe, 0x82, 0xed, 0x33, 0xe4, 0x2d, 0xea, 0xf5, 0x9c, 0xbe,
	0x8e, 0x97, 0x23, 0x64, 0x9c, 0xec, 0x42, 0xc1, 0x35, 0xfb, 0x8e, 0x55, 0x53, 0xea, 0x4a, 0xa3,
	0xa0, 0xcb, 0x05, 0xd9, 0x83, 0xa2, 0x25, 0xdc, 0x6a, 0xb9, 0xba, 0xd2, 0xa8, 0xe8, 0xd1, 0x4a,
	0xfb, 0x45, 0x81, 0x9d, 0x44, 0x08, 0xe6, 0x53, 0x8f, 0xe1, 0x9b, 0xc5, 0x20, 0x8f, 0x01, 0x30,
	0x08, 0x68, 0x60, 0x58, 0xd4, 0xc6, 0x5a, 0x5e, 0x1c, 0x29, 0x09, 0x4b, 0x8b, 0xda, 0x48, 0x3e,
	0x84, 0xaa, 0xdc, 0x76, 0x91, 0x31, 0xb3, 0x8f, 0x35, 0xb5, 0xae, 0x34, 0x4a, 0x7a, 0x45, 0x18,
	0x5f, 0x48, 0x9b, 0x76, 0x0c, 0xe4, 0x68, 0xc8, 0x31, 0x58, 0x85, 0xcb, 0x6f, 0x0a, 0x3c, 0x9c,
	0x0a, 0xf2, 0xd6, 0xd8, 0x7c, 0x06, 0x3b, 0x67, 0x03, 0xfa, 0xd3, 0x12, 0x64, 0xb4, 0x5f, 0x15,
	0x20, 0x49, 0xdf, 0xb7, 0x86, 0xb9, 0x01, 0xdb, 0xa7, 0x0e, 0xe3, 0xe7, 0xd4, 0x77, 0xac, 0xc5,
	0x90, 0xc3, 0x9a, 0x49, 0xb8, 0x66, 0x21, 0xe6, 0xa1, 0x1b, 0xab, 0xe5, 0xea, 0xf9, 0x46, 0x49,
	0x8f, 0x56, 0x6b, 0x41, 0xfc, 0x1d, 0xec, 0x9e, 0x20, 0xb3, 0x02, 0xa7, 0x8b, 0xd9, 0xa8, 0xc3,
	0x1b, 0xc5, 0xdd, 0x86, 0x67, 0xba, 0x28, 0xf4, 0x2b, 0xe9, 0x25, 0x61, 0x79, 0x69, 0xba, 0xa8,
	0xfd, 0xad, 0xc0, 0xa3, 0x54, 0xb4, 0x85, 0xc4, 0x3e, 0x87, 0x82, 0x38, 0x2c, 0x22, 0x95, 0x0f,
	0x77, 0x9b, 0x53, 0xaf, 0xb4, 0x29, 0x43, 0x48, 0x97, 0xb5, 0x90, 0x1d, 0x03, 0x69, 0x05, 0x68,
	0xf2, 0xd5, 0xa9, 0x92, 0xa7, 0xb0, 0x23, 0xb7, 0x6d, 0xc1, 0xd7, 0xe7, 0x0e, 0xf5, 0x04, 0xaa,
	0x92, 0xbe, 0x2d, 0x36, 0x4e, 0x6e, 0xec, 0x1a, 0x85, 0x87, 0x53, 0xf7, 0x2e, 0x14, 0x65, 0x9a,
	0x68, 0x2e, 0x93, 0x68, 0xfe, 0x16, 0xa2, 0x6d, 0x20, 0x27, 0x38, 0xc4, 0x35, 0x10, 0x0d, 0xb1,
	0x4f, 0x85, 0xba, 0x73, 0xec, 0xa7, 0xf0, 0x48, 0x8a, 0xf5, 0x3c, 0x30, 0xfb, 0x2e, 0x7a, 0x7c,
	0x25, 0xf8, 0xd7, 0x0a, 0xec, 0xa5, 0xc3, 0x2d, 0xa4, 0xf0, 0x0c, 0x36, 0x7b, 0x91, 0x67, 0x54,
	0x96, 0xfb, 0xa9, 0xb2, 0x9c, 0x04, 0x9a, 0x38, 0xae, 0xa5, 0x38, 0xdd, 0xf0, 0xed, 0x84, 0x42,
	0xaf, 0x83, 0x37, 0xf9, 0x00, 0xca, 0x31, 0x3a, 0xc3, 0xb1, 0x05, 0xa4, 0xaa, 0x0e, 0xb1, 0xa9,
	0x6d, 0x6b, 0x01, 0xec, 0xa5, 0xaf, 0xbb, 0xf3, 0xd4, 0x52, 0xd8, 0x8f, 0xdb, 0xc3, 0xfd, 0x90,
	0xfc, 0x47, 0x81, 0xda, 0xec, 0x8d, 0xef, 0x66, 0xfe, 0x2f, 0xe2, 0xe6, 0xf4, 0x4d, 0x40, 0x47,
	0x7e, 0xa6, 0x2e, 0xfd, 0xd0, 0x6b, 0x4a, 0x17, 0x61, 0x11, 0xba, 0xd4, 0xa1, 0x3c, 0xdb, 0x96,
	0x92, 0x26, 0xed, 0x2f, 0x25, 0x6e, 0x49, 0xd1, 0x6d, 0x59, 0x7d, 0x5a, 0x04, 0x9f, 0xd3, 0xa7,
	0x65, 0x08, 0xe9, 0xb2, 0xae, 0xd1, 0x1f, 0xce, 0x46, 0x11, 0x97, 0x2d, 0x9e, 0xa3, 0x7f, 0x2a,
	0x40, 0x92, 0xbe, 0xcb, 0xf2, 0xc8, 0xdf, 0x07, 0x8f, 0x16, 0x6c, 0x7f, 0x4b, 0x1d, 0x6f, 0x89,
	0x84, 0xbe, 0x07, 0x9b, 0x32, 0xa1, 0x8e, 0x2d, 0x44, 0x56, 0xf5, 0x0d, 0xb1, 0x6e, 0xdb, 0x9a,
	0x0b, 0x3b, 0x89, 0x20, 0x77, 0xfe, 0x46, 0x4f, 0x60, 0xe7, 0x14, 0xcd, 0x31, 0xae, 0x06, 0xda,
	0x03, 0x92, 0x8c, 0x72, 0xe7, 0xa8, 0xbf, 0x8e, 0x07, 0xde, 0x6a, 0xb0, 0x27, 0xc3, 0xee, 0xbe,
	0x70, 0x5f, 0x2b, 0xb0, 0xd5, 0xa2, 0x9e, 0x87, 0x56, 0x46, 0x27, 0xfc, 0x12, 0x2a, 0x0c, 0x19,
	0x73, 0xa8, 0x67, 0xf0, 0x57, 0xbe, 0xbc, 0x6e, 0xeb, 0xf0, 0x20, 0x55, 0xc1, 0x67, 0xd2, 0xe5,
	0xfc, 0x95, 0x8f, 0x7a, 0x99, 0xdd, 0x2c, 0x52, 0x8d, 0x34, 0x9f, 0x6e, 0xa4, 0x4f, 0xa0, 0x92,
	0x68, 0xa4, 0xac, 0xa6, 0xd6, 0xf3, 0x8d, 0xaa, 0x5e, 0xbe, 0xe9, 0xa4, 0x4c, 0xfb, 0x14, 0x1e,
	0x4c, 0x80, 0x2e, 0x92, 0x45, 0x7b, 0x01, 0x6a, 0xc7, 0xf1, 0xfa, 0x73, 0x78, 0x10, 0x50, 0xd1,
	0x1a, 0xd0, 0xa8, 0x67, 0x89, 0x6f, 0xf2, 0x3e, 0x94, 0xba, 0x01, 0xbd, 0xc0, 0x20, 0x6e, 0xe2,
	0xaa, 0xbe, 0x29, 0x0d, 0x6d, 0x5b, 0xbb, 0x02, 0xb5, 0x43, 0xdf, 0x28, 0xdc, 0xc7, 0xb0, 0xc5,
	0x30, 0x18, 0x63, 0x60, 0x8c, 0x31, 0x60, 0x71, 0x03, 0xac, 0xea, 0x55, 0x69, 0xfd, 0x41, 0x1a,
	0xc3, 0xe1, 0x11, 0xb9, 0x71, 0xc7, 0x95, 0xef, 0x57, 0xd5, 0x41, 0x9a, 0xce, 0x1d, 0x17, 0xb5,
	0xdf, 0x15, 0x80, 0xce, 0x28, 0x23, 0x2f, 0x04, 0xd4, 0xf0, 0x5f, 0x32, 0xfa, 0x97, 0x10, 0xdf,
	0x64, 0x1f, 0x36, 0x18, 0x5e, 0x1a, 0xde, 0xc8, 0x8d, 0xd8, 0x14, 0x19, 0x5e, 0xbe, 0x1c, 0xb9,
	0xe1, 0x86, 0x47, 0x6d, 0x0c, 0x69, 0xca, 0x76, 0x51, 0x0c, 0x97, 0x6d, 0x3b, 0x3d, 0xc8, 0x0a,
	0x33, 0x83, 0xec, 0x67, 0x05, 0xca, 0x02, 0x4b, 0x56, 0x45, 0xae, 0x32, 0x2e, 0x43, 0x87, 0xa1,
	0xc9, 0xb8, 0x41, 0x7b, 0x3d, 0x86, 0x3c, 0x96, 0x24, 0x34, 0x7d, 0x2f, 0x2c, 0xda, 0x1f, 0x39,
	0xa8, 0x3c, 0x47, 0x6e, 0x0d, 0x16, 0x8b, 0xf2, 0x11, 0x6c, 0xb9, 0xe6, 0x95, 0xd1, 0x35, 0xb9,
	0x35, 0x30, 0x98, 0xf3, 0x5a, 0x62, 0xa9, 0xea, 0x15, 0xd7, 0xbc, 0x3a, 0x0e, 0x8d, 0x67, 0xce,
	0x6b, 0x0c, 0xf3, 0xd4, 0x1b, 0x8e, 0xd8, 0xc0, 0x70, 0x3c, 0x8e, 0xc1, 0xd8, 0x1c, 0xc6, 0x79,
	0x12, 0xd6, 0x76, 0x64, 0x24, 0x1d, 0x78, 0x10, 0x43, 0x94, 0x28, 0x64, 0x79, 0x96, 0x0f, 0x3f,
	0x49, 0xcf, 0xe5, 0x04, 0xb0, 0xa6, 0x74, 0x6d, 0x7b, 0x3d, 0xaa, 0xa7, 0x8f, 0x1f, 0x74, 0x00,
	0x6e, 0xb6, 0xd3, 0xaa, 0x28, 0x33, 0xaa, 0x3c, 0x81, 0x0a, 0xe3, 0x66, 0x30, 0x91, 0x45, 0xf6,
	0x8c, 0xb2, 0xb0, 0x45, 0xba, 0xfc, 0xa7, 0x40, 0x35, 0xba, 0x7e, 0x61, 0x82, 0x6e, 0xab, 0x96,
	0x3d, 0x28, 0x46, 0x81, 0xa3, 0x62, 0x91, 0xab, 0x64, 0x15, 0xa9, 0xf3, 0xaa, 0xa8, 0x30, 0x55,
	0x45, 0xd3, 0xe9, 0x2f, 0x66, 0xa4, 0x7f, 0x23, 0x2b, 0xfd, 0x9b, 0x33, 0xe9, 0xff, 0x37, 0x07,
	0xbb, 0x22, 0x7f, 0x68, 0x2f, 0xc3, 0xf6, 0x08, 0x0a, 0x0e, 0x47, 0x97, 0x45, 0xe3, 0xf6, 0x69,
	0x2a, 0x5f, 0xb7, 0x45, 0x92, 0x49, 0x44, 0x5b, 0x97, 0x27, 0xd3, 0x90, 0xf2, 0x69, 0x48, 0x07,
	0xd7, 0x0a, 0x6c, 0x44, 0x67, 0x26, 0xea, 0x2a, 0xb7, 0xaa, 0x9b, 0x9b, 0xa7, 0xee, 0x92, 0x6f,
	0x74, 0x5a, 0xdd, 0x42, 0x86, 0xba, 0xc5, 0x99, 0x27, 0x7c, 0x04, 0xf9, 0x23, 0xeb, 0x62, 0x7e,
	0x61, 0x4c, 0xa6, 0x48, 0x55, 0x17, 0xdf, 0x64, 0x1b, 0xf2, 0x2e, 0xeb, 0x47, 0xcd, 0x3a, 0xfc,
	0xd4, 0x1e, 0x43, 0xa1, 0x35, 0xa4, 0xf3, 0xf4, 0x3e, 0x2e, 0xfe, 0xa8, 0x36, 0xbf, 0xf0, 0xbb,
	0xdd, 0xa2, 0xd0, 0xf7, 0xd9, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26, 0x8b, 0x51, 0xac, 0x00,
	0x13, 0x00, 0x00,
}
