// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionType int32

const (
	SessionType_ADMIN      SessionType = 0
	SessionType_PUBLISHER  SessionType = 1
	SessionType_SUBSCRIBER SessionType = 2
)

var SessionType_name = map[int32]string{
	0: "ADMIN",
	1: "PUBLISHER",
	2: "SUBSCRIBER",
}

var SessionType_value = map[string]int32{
	"ADMIN":      0,
	"PUBLISHER":  1,
	"SUBSCRIBER": 2,
}

func (x SessionType) String() string {
	return proto.EnumName(SessionType_name, int32(x))
}

func (SessionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

type Group struct {
	GroupId              uint64   `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	OwnerId              uint64   `protobuf:"varint,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	GroupName            string   `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetGroupId() uint64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *Group) GetOwnerId() uint64 {
	if m != nil {
		return m.OwnerId
	}
	return 0
}

func (m *Group) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

type Fragment struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LastOffset           uint64   `protobuf:"varint,2,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	BrokerAddresses      []string `protobuf:"bytes,3,rep,name=broker_addresses,json=brokerAddresses,proto3" json:"broker_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fragment) Reset()         { *m = Fragment{} }
func (m *Fragment) String() string { return proto.CompactTextString(m) }
func (*Fragment) ProtoMessage()    {}
func (*Fragment) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *Fragment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fragment.Unmarshal(m, b)
}
func (m *Fragment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fragment.Marshal(b, m, deterministic)
}
func (m *Fragment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fragment.Merge(m, src)
}
func (m *Fragment) XXX_Size() int {
	return xxx_messageInfo_Fragment.Size(m)
}
func (m *Fragment) XXX_DiscardUnknown() {
	xxx_messageInfo_Fragment.DiscardUnknown(m)
}

var xxx_messageInfo_Fragment proto.InternalMessageInfo

func (m *Fragment) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Fragment) GetLastOffset() uint64 {
	if m != nil {
		return m.LastOffset
	}
	return 0
}

func (m *Fragment) GetBrokerAddresses() []string {
	if m != nil {
		return m.BrokerAddresses
	}
	return nil
}

type Topic struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string      `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	NumFragments         uint32      `protobuf:"varint,3,opt,name=num_fragments,json=numFragments,proto3" json:"num_fragments,omitempty"`
	ReplicationFactor    uint32      `protobuf:"varint,4,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	Fragments            []*Fragment `protobuf:"bytes,5,rep,name=fragments,proto3" json:"fragments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Topic) GetNumFragments() uint32 {
	if m != nil {
		return m.NumFragments
	}
	return 0
}

func (m *Topic) GetReplicationFactor() uint32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

func (m *Topic) GetFragments() []*Fragment {
	if m != nil {
		return m.Fragments
	}
	return nil
}

func init() {
	proto.RegisterEnum("shapleq.proto.SessionType", SessionType_name, SessionType_value)
	proto.RegisterType((*Group)(nil), "shapleq.proto.Group")
	proto.RegisterType((*Fragment)(nil), "shapleq.proto.Fragment")
	proto.RegisterType((*Topic)(nil), "shapleq.proto.Topic")
}

func init() {
	proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd)
}

var fileDescriptor_871986018790d2fd = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0xce, 0x93, 0x40,
	0x14, 0xc5, 0xe5, 0xdf, 0xe7, 0xc7, 0x45, 0x2a, 0xde, 0x8d, 0xb8, 0x30, 0x92, 0xba, 0x41, 0x13,
	0x31, 0xd1, 0x18, 0xd7, 0x45, 0x5b, 0x25, 0xd1, 0x6a, 0x86, 0x76, 0x63, 0x4c, 0xc8, 0x94, 0x19,
	0x2a, 0xb1, 0x30, 0xe3, 0x0c, 0x8d, 0xf1, 0x0d, 0x7d, 0x2c, 0xc3, 0xd0, 0xa6, 0x75, 0x77, 0xcf,
	0xef, 0xdc, 0x7b, 0x38, 0x0c, 0x00, 0xa3, 0x03, 0xcd, 0xa4, 0x12, 0x83, 0xc0, 0x50, 0xff, 0xa0,
	0xf2, 0xc0, 0x7f, 0x4d, 0x72, 0xfe, 0x1d, 0xbc, 0x0f, 0x4a, 0x1c, 0x25, 0x3e, 0x82, 0xdb, 0xfd,
	0x38, 0x54, 0x2d, 0x8b, 0xad, 0xc4, 0x4a, 0x5d, 0x72, 0xd7, 0xe8, 0x82, 0x8d, 0x96, 0xf8, 0xdd,
	0x73, 0x35, 0x5a, 0xf6, 0x64, 0x19, 0x5d, 0x30, 0x7c, 0x0c, 0x30, 0x5d, 0xf5, 0xb4, 0xe3, 0xb1,
	0x93, 0x58, 0xa9, 0x4f, 0x7c, 0x43, 0xd6, 0xb4, 0xe3, 0xf3, 0x06, 0x6e, 0x57, 0x8a, 0xee, 0x3b,
	0xde, 0x0f, 0x38, 0x03, 0xfb, 0x14, 0x1d, 0x12, 0xbb, 0x65, 0xf8, 0x04, 0x82, 0x03, 0xd5, 0x43,
	0x25, 0x9a, 0x46, 0xf3, 0xe1, 0x14, 0x0c, 0x23, 0xfa, 0x62, 0x08, 0x3e, 0x83, 0x68, 0xa7, 0xc4,
	0x4f, 0xae, 0x2a, 0xca, 0x98, 0xe2, 0x5a, 0x73, 0x1d, 0x3b, 0x89, 0x93, 0xfa, 0xe4, 0xfe, 0xc4,
	0x17, 0x67, 0x3c, 0xff, 0x6b, 0x81, 0xb7, 0x11, 0xb2, 0xad, 0x11, 0xc1, 0x35, 0x55, 0x2c, 0x53,
	0xc5, 0xcc, 0x98, 0x40, 0xc0, 0xb8, 0xae, 0x55, 0x2b, 0x87, 0x56, 0xf4, 0xe6, 0x4b, 0x3e, 0xb9,
	0x46, 0xf8, 0x14, 0xc2, 0xfe, 0xd8, 0x55, 0xcd, 0xa9, 0xab, 0x36, 0x7f, 0x12, 0x92, 0x7b, 0xfd,
	0xb1, 0x3b, 0xf7, 0xd7, 0xf8, 0x02, 0x50, 0x71, 0x79, 0x68, 0x6b, 0x3a, 0xde, 0x54, 0x0d, 0xad,
	0x07, 0xa1, 0x62, 0xd7, 0x6c, 0x3e, 0xb8, 0x72, 0x56, 0xc6, 0xc0, 0x37, 0xe0, 0x5f, 0xf2, 0xbc,
	0xc4, 0x49, 0x83, 0x57, 0x0f, 0xb3, 0xff, 0x1e, 0x3f, 0x3b, 0x67, 0x93, 0xcb, 0xe6, 0xf3, 0xb7,
	0x10, 0x94, 0x5c, 0xeb, 0x56, 0xf4, 0x9b, 0x3f, 0x92, 0xa3, 0x0f, 0xde, 0xe2, 0xfd, 0xe7, 0x62,
	0x1d, 0xdd, 0xc1, 0x10, 0xfc, 0xaf, 0xdb, 0xfc, 0x53, 0x51, 0x7e, 0x5c, 0x92, 0xc8, 0xc2, 0x19,
	0x40, 0xb9, 0xcd, 0xcb, 0x77, 0xa4, 0xc8, 0x97, 0x24, 0xb2, 0xf3, 0x9b, 0x6f, 0x6e, 0xf6, 0x52,
	0xee, 0x76, 0x37, 0x26, 0xfb, 0xf5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xc3, 0xbf, 0xfd,
	0xf5, 0x01, 0x00, 0x00,
}
