// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SessionType int32

const (
	SessionType_ADMIN      SessionType = 0
	SessionType_PUBLISHER  SessionType = 1
	SessionType_SUBSCRIBER SessionType = 2
)

var SessionType_name = map[int32]string{
	0: "ADMIN",
	1: "PUBLISHER",
	2: "SUBSCRIBER",
}

var SessionType_value = map[string]int32{
	"ADMIN":      0,
	"PUBLISHER":  1,
	"SUBSCRIBER": 2,
}

func (x SessionType) String() string {
	return proto.EnumName(SessionType_name, int32(x))
}

func (SessionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

type FragmentInfo struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LastOffset           uint64   `protobuf:"varint,2,opt,name=last_offset,json=lastOffset,proto3" json:"last_offset,omitempty"`
	BrokerAddresses      []string `protobuf:"bytes,3,rep,name=broker_addresses,json=brokerAddresses,proto3" json:"broker_addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FragmentInfo) Reset()         { *m = FragmentInfo{} }
func (m *FragmentInfo) String() string { return proto.CompactTextString(m) }
func (*FragmentInfo) ProtoMessage()    {}
func (*FragmentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *FragmentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FragmentInfo.Unmarshal(m, b)
}
func (m *FragmentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FragmentInfo.Marshal(b, m, deterministic)
}
func (m *FragmentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentInfo.Merge(m, src)
}
func (m *FragmentInfo) XXX_Size() int {
	return xxx_messageInfo_FragmentInfo.Size(m)
}
func (m *FragmentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentInfo proto.InternalMessageInfo

func (m *FragmentInfo) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FragmentInfo) GetLastOffset() uint64 {
	if m != nil {
		return m.LastOffset
	}
	return 0
}

func (m *FragmentInfo) GetBrokerAddresses() []string {
	if m != nil {
		return m.BrokerAddresses
	}
	return nil
}

type TopicInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ReplicationFactor    uint32   `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor,proto3" json:"replication_factor,omitempty"`
	FragmentIds          []uint32 `protobuf:"varint,4,rep,packed,name=fragmentIds,proto3" json:"fragmentIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicInfo) Reset()         { *m = TopicInfo{} }
func (m *TopicInfo) String() string { return proto.CompactTextString(m) }
func (*TopicInfo) ProtoMessage()    {}
func (*TopicInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *TopicInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicInfo.Unmarshal(m, b)
}
func (m *TopicInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicInfo.Marshal(b, m, deterministic)
}
func (m *TopicInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicInfo.Merge(m, src)
}
func (m *TopicInfo) XXX_Size() int {
	return xxx_messageInfo_TopicInfo.Size(m)
}
func (m *TopicInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TopicInfo proto.InternalMessageInfo

func (m *TopicInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TopicInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TopicInfo) GetReplicationFactor() uint32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

func (m *TopicInfo) GetFragmentIds() []uint32 {
	if m != nil {
		return m.FragmentIds
	}
	return nil
}

type Topic struct {
	TopicName            string                  `protobuf:"bytes,1,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	Offsets              []*Topic_FragmentOffset `protobuf:"bytes,2,rep,name=offsets,proto3" json:"offsets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *Topic) GetOffsets() []*Topic_FragmentOffset {
	if m != nil {
		return m.Offsets
	}
	return nil
}

type Topic_FragmentOffset struct {
	FragmentId           uint32   `protobuf:"varint,1,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	StartOffset          uint64   `protobuf:"varint,2,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Topic_FragmentOffset) Reset()         { *m = Topic_FragmentOffset{} }
func (m *Topic_FragmentOffset) String() string { return proto.CompactTextString(m) }
func (*Topic_FragmentOffset) ProtoMessage()    {}
func (*Topic_FragmentOffset) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2, 0}
}

func (m *Topic_FragmentOffset) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic_FragmentOffset.Unmarshal(m, b)
}
func (m *Topic_FragmentOffset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic_FragmentOffset.Marshal(b, m, deterministic)
}
func (m *Topic_FragmentOffset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic_FragmentOffset.Merge(m, src)
}
func (m *Topic_FragmentOffset) XXX_Size() int {
	return xxx_messageInfo_Topic_FragmentOffset.Size(m)
}
func (m *Topic_FragmentOffset) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic_FragmentOffset.DiscardUnknown(m)
}

var xxx_messageInfo_Topic_FragmentOffset proto.InternalMessageInfo

func (m *Topic_FragmentOffset) GetFragmentId() uint32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *Topic_FragmentOffset) GetStartOffset() uint64 {
	if m != nil {
		return m.StartOffset
	}
	return 0
}

func init() {
	proto.RegisterEnum("shapleq.proto.SessionType", SessionType_name, SessionType_value)
	proto.RegisterType((*FragmentInfo)(nil), "shapleq.proto.FragmentInfo")
	proto.RegisterType((*TopicInfo)(nil), "shapleq.proto.TopicInfo")
	proto.RegisterType((*Topic)(nil), "shapleq.proto.Topic")
	proto.RegisterType((*Topic_FragmentOffset)(nil), "shapleq.proto.Topic.FragmentOffset")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4e, 0xab, 0x40,
	0x14, 0x87, 0x2f, 0x7f, 0xda, 0x1b, 0x0e, 0xa5, 0x97, 0x3b, 0x2b, 0x72, 0x93, 0x1b, 0xb1, 0x6e,
	0xd0, 0x44, 0x4c, 0x74, 0xe1, 0xca, 0x45, 0xd1, 0x36, 0x92, 0x68, 0x35, 0x43, 0xbb, 0x71, 0x43,
	0xa6, 0x30, 0x28, 0xda, 0x32, 0x38, 0x33, 0x1b, 0x5f, 0xc3, 0xd7, 0xf1, 0xe5, 0x0c, 0x43, 0x50,
	0xea, 0xee, 0x9c, 0xef, 0x64, 0xce, 0xf9, 0xcd, 0x07, 0x90, 0x13, 0x49, 0xc2, 0x9a, 0x33, 0xc9,
	0x90, 0x23, 0x9e, 0x48, 0xbd, 0xa1, 0xaf, 0x6d, 0x3b, 0x79, 0x86, 0xd1, 0x9c, 0x93, 0xc7, 0x2d,
	0xad, 0x64, 0x5c, 0x15, 0x0c, 0x8d, 0x41, 0x2f, 0x73, 0x4f, 0xf3, 0xb5, 0xc0, 0xc1, 0x7a, 0x99,
	0xa3, 0x3d, 0xb0, 0x37, 0x44, 0xc8, 0x94, 0x15, 0x85, 0xa0, 0xd2, 0xd3, 0x7d, 0x2d, 0x30, 0x31,
	0x34, 0xe8, 0x4e, 0x11, 0x74, 0x08, 0xee, 0x9a, 0xb3, 0x17, 0xca, 0x53, 0x92, 0xe7, 0x9c, 0x0a,
	0x41, 0x85, 0x67, 0xf8, 0x46, 0x60, 0xe1, 0x3f, 0x2d, 0x9f, 0x76, 0x78, 0xf2, 0xae, 0x81, 0xb5,
	0x64, 0x75, 0x99, 0xa9, 0x4b, 0x08, 0xcc, 0x8a, 0x6c, 0xa9, 0xba, 0x65, 0x61, 0x55, 0x23, 0x1f,
	0xec, 0x9c, 0x8a, 0x8c, 0x97, 0xb5, 0x2c, 0x59, 0xa5, 0xae, 0x59, 0xb8, 0x8f, 0xd0, 0x31, 0x20,
	0x4e, 0xeb, 0x4d, 0x99, 0x91, 0xa6, 0x4d, 0x0b, 0x92, 0x49, 0xc6, 0x3d, 0x43, 0xe5, 0xfd, 0xdb,
	0x9b, 0xcc, 0xd5, 0xa0, 0x59, 0x58, 0x74, 0xdf, 0xcb, 0x85, 0x67, 0xfa, 0x46, 0xe0, 0xe0, 0x3e,
	0x9a, 0x7c, 0x68, 0x30, 0x50, 0xa1, 0xd0, 0x7f, 0x00, 0xd9, 0x14, 0x69, 0x2f, 0x96, 0xa5, 0xc8,
	0xa2, 0xc9, 0x76, 0x01, 0xbf, 0x5b, 0x09, 0xc2, 0xd3, 0x7d, 0x23, 0xb0, 0x4f, 0x0f, 0xc2, 0x1d,
	0x95, 0xa1, 0xda, 0x12, 0x76, 0x36, 0x5b, 0x3d, 0xb8, 0x7b, 0xf3, 0x6f, 0x09, 0xe3, 0xdd, 0x51,
	0xa3, 0xb6, 0x0b, 0x92, 0x7e, 0x39, 0x87, 0xef, 0x6c, 0x68, 0x1f, 0x46, 0x42, 0x12, 0xfe, 0x43,
	0xbe, 0xad, 0x58, 0xbb, 0xe3, 0xe8, 0x1c, 0xec, 0x84, 0x0a, 0x51, 0xb2, 0x6a, 0xf9, 0x56, 0x53,
	0x64, 0xc1, 0x60, 0x7a, 0x75, 0x1b, 0x2f, 0xdc, 0x5f, 0xc8, 0x01, 0xeb, 0x7e, 0x15, 0xdd, 0xc4,
	0xc9, 0xf5, 0x0c, 0xbb, 0x1a, 0x1a, 0x03, 0x24, 0xab, 0x28, 0xb9, 0xc4, 0x71, 0x34, 0xc3, 0xae,
	0x1e, 0x0d, 0x1f, 0xcc, 0xf0, 0xa4, 0x5e, 0xaf, 0x87, 0x2a, 0xfb, 0xd9, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x5c, 0x63, 0xa0, 0x93, 0x23, 0x02, 0x00, 0x00,
}
